### ISSUE TITLE
GoLand support

### ISSUE THREAD

**Issue by aneshas** [timKraeuter/VisualDebugger#12]
Hi, 

first of all, amazing work! My question would be - have you considered supporting Jetbrains Goland?

Thanks

**Comment by aneshas** [comment]
Ok thank you, will take a look

**Comment by timKraeuter** [comment]
Generally, we would want to hook into the debugging process to get variables/objects in scope during debugging.
The rest should be rather easy to implement due to the plugin's architecture.

**Comment by timKraeuter** [comment]
I couldn't find a GoLand API to access the debug information, so I asked the [question in the forum](https://intellij-support.jetbrains.com/hc/en-us/community/posts/14683995888018-Accessing-Go-debug-information-variables-while-debugging-with-a-plugin-GoLand-).

**Comment by timKraeuter** [comment]
There currently is no API to do that, see [forum question](https://intellij-support.jetbrains.com/hc/en-us/community/posts/14683995888018-Accessing-Go-debug-information-variables-while-debugging-with-a-plugin-GoLand-).

**Comment by aneshas** [comment]
Hey, I also couldn't find any and figured the only way to access that information would be by interacting directly with the debugger (Delve) via it's api (json-rpc or DAP https://github.com/go-delve/delve/blob/master/Documentation/api/ClientHowto.md) but that would be a lot more involved I guess.

**Comment by timKraeuter** [comment]
It is probably more involved, but, most importantly, it bypasses the IDE. Then, we would build a standalone Visual Debugger, which would be cool, but I think IDE integration is important.
I will keep you updated if something changes in the issues linked in the forum question. I might also get the chance to talk to some JetBrains people next year.

**Comment by aneshas** [comment]
Yes true, was actually considering the delve api in the context of building a separate goland specific plugin, but having the integration as a part of this one would definitely be cooler. Thanks

**Comment by timKraeuter** [comment]
In the end, you only know once you try. Feel free to go ahead and reuse parts of this plugin. At least you will learn a lot.
